# Generated by Django 3.2.3 on 2021-09-02 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15, verbose_name='téléphone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
                ('contacts', models.ManyToManyField(to='contacts.Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur personnalisé',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customuser', verbose_name='utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
